[package]
name = "karabiner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
clipboard = "0.5.0"
sha2 = "0.10.6"
chrono = "0.4.19"
hex-literal = "0.3"